### ISSUE TITLE
Give additional guidance on Github Flavored Markdown

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-mimi/draft-ietf-mimi-content#23]
From timo:

Using https://github.github.com/gfm/ as a basis, I have identified the following problems with GFM:

- Some useful features are extensions: If we go with GFM, we should at least specify what extensions to use
- We do not want syntax for inline media: Instead, use MIMI MultiPart
- We do not want syntax for raw html: This increases the scope a lot, since GFM does not define a whitelist. Clients would also need to impose additional security constraints.
- No smart timestamps that respect timezones (see https://discord.com/developers/docs/reference#message-formatting-timestamp-styles )
- No built-in interactive elements like polls.
- "Soft line breaks" may be ignored (decided by renderer): If the user typed a newline, they probably want a newline
- Ordered lists must increment by 1 and strip leading zeros 001 -> 1: Markup languages should not change the meaning of the input
- No spoiler syntax for messages or media: In Discord it is ||secret||
- No autolinks for mimi://
- ~~Emojis can have different meanings between platforms, like gun vs water pistol: Maybe clients can annotate what emoji style they use?~~

I also thought about math support, but I think that should not be part of the text message and instead be a different MIMI MultiPart entry of another content type.

**Comment by rohanmahy** [comment]
The emoji issue is clear. Unicode describes the semantics of an emoji, not it's presentation.

**Comment by rohanmahy** [comment]
Rohan to paste in discussion on the mailing list and add it to the document

**Comment by timokoesters** [comment]
> [Polls, spoilers, smart timestamps, ...] are extensions and not defined in the reference to GFM

Should Mimi still give guidance on this? Should we allow clients to agree on a set of extensions using room policy?

> I think these two are confusing what was input and the Markdown sent over the wire.

You are right, some of the issues can be handled if we add a translation layer between user input and transmitted markdown. However, not all of them:
`Ordered lists must increment by 1 and strip leading zeros 001 -> 1`
What if the user wants to send an ordered list that increases by 10?

P.S. Ironically, in your message you did not leave an empty line between quote and response, making it harder to read. GFM has some problems.

**Comment by rohanmahy** [comment]
Re: Extensions, someone can define a new variant that has other extensions, but I think it will be called something else. The point of GFM is that it is relatively well documented.

> What if the user wants to send an ordered list that increases by 10?
I am ok saying they can use HTML, or they can use a code block. Doing that isn't a feature of GFM markdown.

Regarding the empty line, the GFM spec actually mentions that not having this line is often deisrable, and I happen to agree. Chacun à son gout.

**Comment by mar-v-in** [comment]
As a side note: The [registration for the text/markdown media type](https://www.iana.org/assignments/media-types/text/markdown) from RFC 7763 declares the following applications to use this media type:
> Markdown conversion tools, Markdown WYSIWYG editors, and plain text editors and viewers; markup processor targets indirectly use Markdown (e.g., web browsers for Markdown converted to HTML).

Further, RFC 7763 says:
> The paradigmatic use case for text/markdown is the Markdown editor: an application that presents Markdown content (which looks like an email or other piece of plain-text writing) alongside a published format, so that an author can see results instantaneously and can tweak his or her input in real time.

So, following from that, I would assume that if text/markdown is included in the messages, it is for further editing the message, not for the receiving client to process and display it. For displaying, we should include a format suitable for publication in the message (RFC 7763 seems to suggest HTML for that, but other formats might be suitable as well). This would mean a rich message that is edited as markdown would then have three representations: 
- text/plain - as fallback for text-only clients
- text/html or any other suitable publishing format - for display
- text/markdown;variant=GFM or any other variant - for editing

This has the further advantage that slight differences in the markdown processing does not cause different clients to display different messages, because only the sending client would process the markdown, so the sending user knows and sees exactly how it was processed.

**Comment by rohanmahy** [comment]
Fixed. defined GFM-MIMI variant. This is just GFM with no Autolinks and no raw HTML of any kind (instead of tagfilter)

**Comment by timokoesters** [comment]
Re: Ordered lists must always increase by 1

I found a workaround that works in the default gfm. Switching the ordered list character between `.` and `)` starts a new list with a new start index. This can be used to write lists like this:

```
1. aaa
3. ccc
2. ddd
100. eee
1. fff

---

1. aaa
3) ccc
2. ddd
100) eee
1. fff
```

1. aaa
3. ccc
2. ddd
100. eee
1. fff

---

1. aaa
3) ccc
2. ddd
100) eee
1. fff

**Comment by rohanmahy** [comment]
Excellent piece of detective work!
thanks,
-r
